---
  clickhouse_networks_default:
    - "::/0"
    - "127.0.0.1"
  clickhouse_profiles_default:
    default:
      max_memory_usage: 10000000000
      use_uncompressed_cashe: 0
      load_balansing: random
      date_time_input_format: best_effort
      max_partitions_per_insert_block: 100
  clickhouse_user_custom:
    logger:
      password: logger
      networks: "{{ clickhouse_networks_default }}"
      profile: "default"
      quota: "default"
      dbs: ["sample"]
  clickhouse_listen_host_default:
    - 0.0.0.0
