---
vektor_config:
  sources:
    simple_file:
      type: file
      read_from: beginning
      acknowledgements: null
      ignore_older_secs: 600
      include:
        - /home/aleksturbo/logs/*.log
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - simple_file
    database: db_logs
    endpoint: http://192.168.153.118:8123
    table: tbl_logs
    auth:
      password: logger
      user: logger
    acknowledgements: null
    compression: gzip
    encoding: null
    healthcheck: null
    skip_unknown_fields: null
    